# cache.sdc
# Timing constraints for cache_top
# Project: Parameterized Cache Memory Subsystem
# Technology: SkyWater SKY130A / sky130_fd_sc_hd
#
# Based on the actual cache_top RTL:
#   clock : clk
#   inputs: reset, cpu_req_valid, cachereq_addr, cachereq_data,
#           cachereq_opaque, cachereq_type, cachereq_len, cpu_resp_ready,
#           mem_req_ready, mem_resp_valid, mem_resp_rdata
#   outputs: cpu_req_ready, cpu_resp_valid, cpu_resp_data,
#            cpu_resp_opaque, cpu_resp_len, mem_req_valid, mem_req_write,
#            mem_req_addr, mem_req_wdata
#
# Clock period is 5.0 ns, matching design_setup.tcl.

# ============================================================
# 1. CLOCK
# ============================================================

create_clock -name clk -period 5.0 -waveform {0 2.5} [get_ports clk]

# Clock uncertainty from design_setup.tcl
set_clock_uncertainty -setup 0.050 [get_clocks clk]
set_clock_uncertainty -hold  0.050 [get_clocks clk]

# Clock transition assumption
set_clock_transition 0.10 [get_clocks clk]

# ============================================================
# 2. INPUT DELAYS
# ============================================================
# External interface is budgeted with 0.50 ns before the active clock edge.
# These are synchronous functional interfaces; reset is also synchronous
# in cache_controller.v (always @(posedge clk)).

set_input_delay 0.50 -clock clk [get_ports reset]
set_input_delay 0.50 -clock clk [get_ports cpu_req_valid]
set_input_delay 0.50 -clock clk [get_ports cachereq_addr]
set_input_delay 0.50 -clock clk [get_ports cachereq_data]
set_input_delay 0.50 -clock clk [get_ports cachereq_opaque]
set_input_delay 0.50 -clock clk [get_ports cachereq_type]
set_input_delay 0.50 -clock clk [get_ports cachereq_len]
set_input_delay 0.50 -clock clk [get_ports cpu_resp_ready]
set_input_delay 0.50 -clock clk [get_ports mem_req_ready]
set_input_delay 0.50 -clock clk [get_ports mem_resp_valid]
set_input_delay 0.50 -clock clk [get_ports mem_resp_rdata]

# ============================================================
# 3. OUTPUT DELAYS
# ============================================================
# External receiver is assumed to consume 0.50 ns of the 5 ns cycle.

set_output_delay 0.50 -clock clk [get_ports cpu_req_ready]
set_output_delay 0.50 -clock clk [get_ports cpu_resp_valid]
set_output_delay 0.50 -clock clk [get_ports cpu_resp_data]
set_output_delay 0.50 -clock clk [get_ports cpu_resp_opaque]
set_output_delay 0.50 -clock clk [get_ports cpu_resp_len]
set_output_delay 0.50 -clock clk [get_ports mem_req_valid]
set_output_delay 0.50 -clock clk [get_ports mem_req_write]
set_output_delay 0.50 -clock clk [get_ports mem_req_addr]
set_output_delay 0.50 -clock clk [get_ports mem_req_wdata]

# ============================================================
# 4. INPUT TRANSITION / OUTPUT LOAD
# ============================================================
# Conservative initial assumptions for physical synthesis.
# These can be refined after actual package/system interface data
# becomes available.

set_input_transition 0.10 [get_ports reset]
set_input_transition 0.10 [get_ports cpu_req_valid]
set_input_transition 0.10 [get_ports cachereq_addr]
set_input_transition 0.10 [get_ports cachereq_data]
set_input_transition 0.10 [get_ports cachereq_opaque]
set_input_transition 0.10 [get_ports cachereq_type]
set_input_transition 0.10 [get_ports cachereq_len]
set_input_transition 0.10 [get_ports cpu_resp_ready]
set_input_transition 0.10 [get_ports mem_req_ready]
set_input_transition 0.10 [get_ports mem_resp_valid]
set_input_transition 0.10 [get_ports mem_resp_rdata]

set_load 0.05 [get_ports cpu_req_ready]
set_load 0.05 [get_ports cpu_resp_valid]
set_load 0.05 [get_ports cpu_resp_data]
set_load 0.05 [get_ports cpu_resp_opaque]
set_load 0.05 [get_ports cpu_resp_len]
set_load 0.05 [get_ports mem_req_valid]
set_load 0.05 [get_ports mem_req_write]
set_load 0.05 [get_ports mem_req_addr]
set_load 0.05 [get_ports mem_req_wdata]

# ============================================================
# 5. FALSE / ASYNCHRONOUS PATHS
# ============================================================
# No false paths are declared.
# reset is synchronous according to cache_controller.v, so it remains
# a timed input.

# ============================================================
# 6. DESIGN RULE CONSTRAINTS
# ============================================================

set_max_transition 0.50 [current_design]
set_max_fanout 20 [current_design]

# ============================================================
# 7. BASIC TIMING REPORT COMMANDS
# ============================================================
# These are intentionally comments; reports are generated by the
# Fusion Compiler scripts.

# report_clock
# report_timing -delay_type max -max_paths 20
# report_timing -delay_type min -max_paths 20
# report_constraint -all_violators

# End of cache.sdc
